GestionaleAlbergo/Controllers/ServiziAggiuntiviController.cs
using GestionaleAlbergo.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GestionaleAlbergo.Controllers
{
    [Authorize(Roles = "Admin")]

    public class ServiziAggiuntiviController : Controller
    {
        public List<SelectListItem> TipoServizio
        {
            get
            {
                List<SelectListItem> list = new List<SelectListItem>();
                SelectListItem item = new SelectListItem { Text = "Seleziona", Value = "0" };
                SelectListItem item2 = new SelectListItem { Text = "Colazione in Camera", Value = "Colazione in Camera" };
                SelectListItem item3 = new SelectListItem { Text = "WiFi", Value = "WiFi" };
                SelectListItem item4 = new SelectListItem { Text = "Biancheria Extra", Value = "Biancheria Extra" };
                SelectListItem item5 = new SelectListItem { Text = "Letto Aggiuntivo", Value = "Letto Aggiuntivo" };
                SelectListItem item6 = new SelectListItem { Text = "Culla", Value = "Culla" };
                list.Add(item);
                list.Add(item2);
                list.Add(item3);
                list.Add(item4);
                list.Add(item5);
                list.Add(item6);
                return list;
            }
        }
        // GET: ServiziAggiuntivi
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult CreaServizi()
        {
            ViewBag.tiposervizio = TipoServizio;
            return View();
        }
        [HttpPost]
        public ActionResult CreaServizi(ServiziAggiuntivi c,string tiposervizio)
        {
            c.TipoServizio = tiposervizio;
            ServiziAggiuntivi.AddServizi(c);
            return RedirectToAction("ListaServizi");

        }


        public ActionResult ListaServizi()
        {
            List<ServiziAggiuntivi> c = new List<ServiziAggiuntivi>();
            c = ServiziAggiuntivi.ListServiziAggiuntivi();
            return View(c);
        }

        public ActionResult DettaglioServizi(int id)
        {
            ServiziAggiuntivi c = new ServiziAggiuntivi();
            c = ServiziAggiuntivi.DettaglioServizi(id);
            return View(c);

        }

        public ActionResult ModificaServizi(int id)
        {
            ViewBag.tiposervizio = TipoServizio;
            ServiziAggiuntivi c = new ServiziAggiuntivi();
            c = ServiziAggiuntivi.DettaglioServizi(id);
            return View(c);
        }

        [HttpPost]
        public ActionResult ModificaServizi(ServiziAggiuntivi c,string tiposervizio)
        {
            if (ModelState.IsValid)
            {
                c.TipoServizio = tiposervizio;
                ServiziAggiuntivi.ModificaServizi(c);
                return RedirectToAction("ListaServizi");
            }
            ViewBag.tiposervizio = TipoServizio;
            return View(c);
        }

        public ActionResult Elimina(int id)
        {
            ServiziAggiuntivi.Delete(id);
            return RedirectToAction("ListaServizi");
        }
    }
}

GestionaleAlbergo/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Applicazione ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    @if (User.IsInRole("Admin"))
    {
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark">
            <div class="container">
                @Html.ActionLink("Nome dell'applicazione", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Attiva/Disattiva spostamento" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li>@Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                        <li>@Html.ActionLink("Prenotazioni", "ListaPrenotazioni", "Prenotazioni", new { area = "" }, new { @class = "nav-link" })</li>
                        <li>@Html.ActionLink("Logout", "Logout", "Admin", new { area = "" }, new { @class = "nav-link" })</li>
                        <li>@Html.ActionLink("Clienti", "ListaClienti", "Clienti", new { area = "" }, new { @class = "nav-link" })</li>
                        <li>@Html.ActionLink("Camere", "ListaCamere", "Camere", new { area = "" }, new { @class = "nav-link" })</li>
                        <li>@Html.ActionLink("Servizi Aggiuntivi", "ListaServizi", "ServiziAggiuntivi", new { area = "" }, new { @class = "nav-link" })</li>
                        <li>@Html.ActionLink("Checkout", "Index", "Checkout", new { area = "" }, new { @class = "nav-link" })</li>
                        <li>@Html.ActionLink("Ricerca", "CercaPrenotazioni", "Ricerca", new { area = "" }, new { @class = "nav-link" })</li>
                    </ul>
                </div>
            </div>
        </nav>
    }
    else
    {
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark">
            <div class="container">
                @Html.ActionLink("Nome dell'applicazione", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Attiva/Disattiva spostamento" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li>@Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                        <li>@Html.ActionLink("Login", "Login", "Home", new { area = "" }, new { @class = "nav-link" })</li>

                    </ul>
                </div>
            </div>
        </nav>
    }


    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Applicazione ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>